version: 0.2

env:
  variables:
    NODE_ENV: production

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."

      # Install CDK and TypeScript globally
      - npm install -g aws-cdk typescript

      # Install root project dependencies
      - npm install

      # Install Lambda function dependencies
      - cd lambda && npm install && cd ..

  pre_build:
    commands:
      - echo "Running tests..."
      - npm test || true
      - echo "Tests completed"

  build:
    commands:
      - echo "Building application..."

      # Compile TypeScript → JS
      - npx tsc

      - echo "Synthesizing CDK stacks..."

      # Generate Dev Template
      - npx cdk synth -o cdk.out ChatAppDevStack

      # Generate Prod Template
      - npx cdk synth -o cdk.out ChatAppProdStack

      - echo "Build completed successfully"

  post_build:
    commands:
      - echo "Build finished on `date`"

artifacts:
  base-directory: cdk.out
  files:
    - "**/*"
  name: BuildArtifact

cache:
  paths:
    - "node_modules/**/*"
    - "lambda/node_modules/**/*"
