# buildspec.yml - Instructions for CodeBuild

version: 0.2

# Environment variables
env:
  variables:
    # Can add variables here
    NODE_ENV: production

# Build phases
phases:
  # Phase 1: Install dependencies
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
      - cd lambda && npm install && cd ..
      - npm install -g aws-cdk

  # Phase 2: Pre-build (optional - run tests)
  pre_build:
    commands:
      - echo "Running tests..."
      - npm test || true  # Continue even if tests fail (for demo)
      - echo "Tests completed"

  # Phase 3: Build
  build:
    commands:
      - echo "Building application..."
      - npm run build
      
      - echo "Synthesizing CDK stacks..."
      # Create Dev stack template
      - cdk synth -o cdk.out ChatAppDevStack
      
      # Create Prod stack template
      - cdk synth -o cdk.out ChatAppProdStack
      
      - echo "Build completed successfully"

  # Phase 4: Post-build (optional - cleanup)
  post_build:
    commands:
      - echo "Build finished on `date`"

# Output artifacts
artifacts:
  files:
    - '**/*'
  base-directory: cdk.out
  name: BuildArtifact

# Cache dependencies for faster builds
cache:
  paths:
    - 'node_modules/**/*'
    - 'lambda/node_modules/**/*'