version: 0.2

env:
  variables:
    NODE_ENV: production

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing global dependencies..."
      - npm install -g aws-cdk
      
  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - npm ci
      
      - echo "Installing Lambda dependencies..."
      - cd lambda && npm install && cd ..
      
      - echo "Running tests..."
      - npm test || echo "Tests completed with warnings"

  build:
    commands:
      - echo "Building application..."
      - npm run build
      
      - echo "Synthesizing CDK stacks..."
      - cdk synth ChatAppDevStack -o cdk.out
      - cdk synth ChatAppProdStack -o cdk.out
      
      - echo "Listing generated files..."
      - ls -la cdk.out/
      
      - echo "Build completed successfully"

  post_build:
    commands:
      - echo "Build finished on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: cdk.out
  name: BuildArtifact

cache:
  paths:
    - 'node_modules/**/*'
<<<<<<< HEAD
    - 'lambda/node_modules/**/*'
=======
    - 'lambda/node_modules/**/*'
>>>>>>> d88f8b3 (updated changes)
