version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing CDK CLI and tools..."
      - npm install -g typescript aws-cdk@latest
      
  pre_build:
    commands:
      - echo "Installing root dependencies..."
      - npm ci
      - echo "Installing Lambda dependencies..."
      - cd lambda && npm ci && cd ..
      - echo "Running tests..."
      - npm test || echo "Tests completed"

  build:
    commands:
      - echo "Building TypeScript..."
      - npm run build
      
      - echo "Synthesizing stacks..."
      - npx cdk synth --all
      
      - echo "Publishing assets to S3..."
      - npx cdk-assets publish --path cdk.out/ChatAppDevStack.assets.json --verbose
      - npx cdk-assets publish --path cdk.out/ChatAppProdStack.assets.json --verbose
      
      - echo "Listing synthesized files..."
      - ls -la cdk.out/

artifacts:
  base-directory: cdk.out
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
    - 'lambda/node_modules/**/*'
