version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing global tools..."
      - npm install -g typescript aws-cdk
      
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Installing Lambda dependencies..."
      - cd lambda && npm install && cd ..
      - echo "Running tests..."
      - npm test || echo "Tests done"

  build:
    commands:
      - echo "Building TypeScript..."
      - npm run build
      - echo "Synthesizing stacks..."
      - cdk synth
      - echo "Listing cdk.out contents..."
      - ls -la cdk.out/
      - find cdk.out -type f | head -20

artifacts:
  base-directory: cdk.out
  files:
    - '**/*'
  name: CDKArtifacts
  
cache:
  paths:
    - 'node_modules/**/*'
    - 'lambda/node_modules/**/*'
